return {
  desc = "The standard Don't Starve experience.",
  hideminimap = false,
  id = "SURVIVAL_TOGETHER",
  location = "forest",
  max_playlist_position = 999,
  min_playlist_position = 0,
  name = "Survival",
  numrandom_set_pieces = 4,
  override_level_string = false,
  overrides = {
    alternatehunt = "default",
    angrybees = "default",
    antliontribute = "default",
    autumn = "default",
    balatro = "default",
    bananabush_portalrate = "default",
    basicresource_regrowth = "always",
    bats_setting = "rare",
    bearger = "default",
    beefalo = "default",
    beefaloheat = "default",
    beequeen = "default",
    bees = "default",
    bees_setting = "default",
    berrybush = "often",
    birds = "default",
    boons = "default",
    branching = "default",
    brightmarecreatures = "default",
    bunnymen_setting = "default",
    butterfly = "default",
    buzzard = "default",
    cactus = "default",
    cactus_regrowth = "default",
    carrot = "often",
    carrots_regrowth = "veryfast",
    catcoon = "default",
    catcoons = "default",
    chess = "default",
    cookiecutters = "default",
    crabking = "default",
    crow_carnival = "default",
    darkness = "default",
    day = "default",
    daywalker2 = "default",
    deciduousmonster = "default",
    deciduoustree_regrowth = "default",
    deerclops = "default",
    dragonfly = "default",
    dropeverythingondespawn = "default",
    evergreen_regrowth = "fast",
    extrastartingitems = "default",
    eyeofterror = "default",
    fishschools = "default",
    flint = "mostly",
    flowers = "default",
    flowers_regrowth = "default",
    frograin = "default",
    frogs = "default",
    fruitfly = "default",
    ghostenabled = "always",
    ghostsanitydrain = "always",
    gnarwail = "default",
    goosemoose = "default",
    grass = "often",
    grassgekkos = "default",
    hallowed_nights = "default",
    has_ocean = true,
    healthpenalty = "always",
    hound_mounds = "default",
    houndmound = "default",
    hounds = "default",
    hunger = "default",
    hunt = "default",
    junkyard = "default",
    keep_disconnected_tiles = true,
    klaus = "default",
    krampus = "default",
    layout_mode = "LinkNodesByKeys",
    lessdamagetaken = "none",
    liefs = "default",
    lightcrab_portalrate = "default",
    lightning = "default",
    lightninggoat = "default",
    loop = "default",
    lunarhail_frequency = "default",
    lureplants = "default",
    malbatross = "default",
    marshbush = "default",
    merm = "default",
    merms = "default",
    meteorshowers = "default",
    meteorspawner = "often",
    moles = "default",
    moles_setting = "default",
    monkeytail_portalrate = "default",
    moon_berrybush = "often",
    moon_bullkelp = "default",
    moon_carrot = "default",
    moon_fissure = "default",
    moon_fruitdragon = "default",
    moon_hotspring = "often",
    moon_rock = "often",
    moon_sapling = "often",
    moon_spider = "default",
    moon_spiders = "default",
    moon_starfish = "often",
    moon_tree = "often",
    moon_tree_regrowth = "fast",
    mosquitos = "rare",
    mushroom = "often",
    mutated_hounds = "never",
    no_joining_islands = true,
    no_wormholes_to_disconnected_tiles = true,
    ocean_bullkelp = "default",
    ocean_otterdens = "default",
    ocean_seastack = "ocean_often",
    ocean_shoal = "default",
    ocean_waterplant = "ocean_default",
    ocean_wobsterden = "default",
    otters_setting = "default",
    palmcone_seed_portalrate = "default",
    palmconetree = "default",
    palmconetree_regrowth = "default",
    penguins = "default",
    penguins_moon = "default",
    perd = "default",
    petrification = "default",
    pigs = "default",
    pigs_setting = "default",
    pirateraids = "default",
    ponds = "often",
    portal_spawnrate = "default",
    portalresurection = "none",
    powder_monkey_portalrate = "default",
    prefabswaps_start = "default",
    rabbits = "default",
    rabbits_setting = "default",
    reeds = "default",
    reeds_regrowth = "fast",
    regrowth = "default",
    resettime = "default",
    rifts_enabled = "default",
    rifts_frequency = "default",
    roads = "default",
    rock = "often",
    rock_ice = "often",
    saltstack_regrowth = "default",
    sapling = "mostly",
    season_start = "default",
    seasonalstartingitems = "default",
    shadowcreatures = "default",
    sharkboi = "default",
    sharks = "default",
    spawnmode = "fixed",
    spawnprotection = "default",
    specialevent = "default",
    spider_warriors = "default",
    spiderqueen = "default",
    spiders = "default",
    spiders_setting = "default",
    spring = "default",
    squid = "default",
    stageplays = "default",
    start_location = "default",
    summer = "default",
    summerhounds = "default",
    tallbirds = "default",
    task_set = "default",
    temperaturedamage = "default",
    tentacles = "default",
    terrariumchest = "default",
    touchstone = "default",
    trees = "often",
    tumbleweed = "often",
    twiggytrees_regrowth = "veryfast",
    walrus = "default",
    walrus_setting = "default",
    wanderingtrader_enabled = "always",
    wasps = "default",
    weather = "default",
    wildfires = "default",
    winter = "default",
    winterhounds = "default",
    winters_feast = "default",
    wobsters = "default",
    world_size = "default",
    wormhole_prefab = "wormhole",
    year_of_the_beefalo = "default",
    year_of_the_bunnyman = "default",
    year_of_the_carrat = "default",
    year_of_the_catcoon = "default",
    year_of_the_dragonfly = "default",
    year_of_the_gobbler = "default",
    year_of_the_pig = "default",
    year_of_the_snake = "default",
    year_of_the_varg = "default"
  },
  playstyle = "survival",
  random_set_pieces = {
    "Sculptures_2",
    "Sculptures_3",
    "Sculptures_4",
    "Sculptures_5",
    "Chessy_1",
    "Chessy_2",
    "Chessy_3",
    "Chessy_4",
    "Chessy_5",
    "Chessy_6",
    "Maxwell1",
    "Maxwell2",
    "Maxwell3",
    "Maxwell4",
    "Maxwell6",
    "Maxwell7",
    "Warzone_1",
    "Warzone_2",
    "Warzone_3"
  },
  required_prefabs = { "multiplayer_portal" },
  required_setpieces = { "Sculptures_1", "Maxwell5" },
  settings_desc = "The standard Don't Starve experience.",
  settings_id = "SURVIVAL_TOGETHER",
  settings_name = "Survival",
  substitutes = {},
  version = 4,
  worldgen_desc = "The standard Don't Starve experience.",
  worldgen_id = "SURVIVAL_TOGETHER",
  worldgen_name = "Survival"
}
